import { describe, expect, test } from "vitest";
import { parseEnvText, patchEnvText } from "../scripts/lib/env-file.mjs";

describe("setup environment patching", () => {
  test("preserves unmanaged customization lines, comments, and ordering", () => {
    const source = [
      "# Customer customization",
      "CUSTOM_THEME=midnight",
      "",
      "# VideoFlow managed value",
      "NEXT_PUBLIC_APP_NAME=Acme Video",
      "CUSTOM_PLUGIN=true",
      "",
    ].join("\n");

    expect(patchEnvText(source, {
      NEXT_PUBLIC_APP_NAME: "Acme Studio",
      NEXT_PUBLIC_FEATURE_LIBRARY_DELETE: "false",
    })).toBe([
      "# Customer customization",
      "CUSTOM_THEME=midnight",
      "",
      "# VideoFlow managed value",
      "NEXT_PUBLIC_APP_NAME=Acme Studio",
      "CUSTOM_PLUGIN=true",
      "",
      "NEXT_PUBLIC_FEATURE_LIBRARY_DELETE=false",
      "",
    ].join("\n"));
  });

  test("removes only keys explicitly cleared by the caller", () => {
    expect(patchEnvText("KEEP_ME=yes\nREMOVE_ME=yes\n", {
      REMOVE_ME: null,
    })).toBe("KEEP_ME=yes\n");
  });

  test("creates a documented file and parses its values", () => {
    const result = patchEnvText("", { NEXT_PUBLIC_TEST_MODE: "true" });
    expect(result).toContain("# Generated by `npm run setup`.");
    expect(parseEnvText(result).get("NEXT_PUBLIC_TEST_MODE")).toBe("true");
  });

  test("retains CRLF and trailing layout while changing a managed key", () => {
    const source = "# Custom\r\nCUSTOM_VALUE=yes\r\n\r\nNEXT_PUBLIC_TEST_MODE=false\r\n\r\n";
    expect(patchEnvText(source, { NEXT_PUBLIC_TEST_MODE: "true" })).toBe(
      "# Custom\r\nCUSTOM_VALUE=yes\r\n\r\nNEXT_PUBLIC_TEST_MODE=true\r\n\r\n",
    );
  });
});
