const ENV_LINE = /^([A-Z0-9_]+)=(.*)$/;

export function parseEnvText(source) {
  const values = new Map();
  for (const line of source.split(/\r?\n/)) {
    const match = line.match(ENV_LINE);
    if (match) values.set(match[1], match[2]);
  }
  return values;
}

/**
 * Patch only explicitly managed keys. Unmanaged values, comments, blank lines,
 * ordering, and installer-specific customization notes remain untouched.
 */
export function patchEnvText(source, updates, header = "# Generated by `npm run setup`. This file is ignored by Git.") {
  const requested = new Map(Object.entries(updates));
  const seen = new Set();
  const hasSource = source.length > 0;
  const newline = source.includes("\r\n") ? "\r\n" : "\n";
  const lines = hasSource ? source.split(/\r?\n/) : [header];
  const next = [];

  for (const line of lines) {
    const match = line.match(ENV_LINE);
    const key = match?.[1];
    if (!key || !requested.has(key)) {
      next.push(line);
      continue;
    }

    seen.add(key);
    const value = requested.get(key);
    if (value !== null && value !== "") next.push(`${key}=${value}`);
  }

  const additions = [...requested].filter(([key, value]) => !seen.has(key) && value !== null && value !== "");
  if (additions.length > 0) {
    let insertAt = next.length;
    while (insertAt > 0 && next[insertAt - 1] === "") insertAt -= 1;
    const block = [];
    if (insertAt > 0) block.push("");
    for (const [key, value] of additions) block.push(`${key}=${value}`);
    next.splice(insertAt, 0, ...block);
  }

  const result = next.join(newline);
  return result.endsWith(newline) ? result : `${result}${newline}`;
}
